# PREFIX sets up the namespaces to be used in the query
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX tt: <http://www.trisotech.com/graph/1.0/element#>
PREFIX ttr: <http://www.trisotech.com/graph/1.0/elementRel#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dmn: <http://www.trisotech.com/graph/1.0/decision/element#>

# SPARQL queries only get the LATEST version information for all models

SELECT DISTINCT ?fromModel ?fromMimetype ?relType ?toModel ?toMimetype
FROM NAMED ?
WHERE {
GRAPH ? {
  {
    ?from ?relType ?rel .
    # relations can be as semantic, copyOf or reuse, and dmn->dmn are includes
    FILTER(?relType in(ttr:semantic, ttr:copyOf, ttr:reuse, dmn:include))
    ?rel ttr:ref? ?toElement .
    # remove references to self
    FILTER (!EXISTS { ?toElement rdf:type  tt:Ref . } ) .
    ?from ttr:owner? ?fromModel .
    ?fromModel a tt:Model .
    ?fromModel ttr:mimeType ?fromMimetype .
    ?toElement ttr:owner? ?toModel .
    ?toModel a tt:Model .
    ?toModel ttr:mimeType ?toMimetype
  }
}
}
GROUP BY ?fromModel ?fromMimetype ?relType ?toModel ?toMimetype
