# PREFIX sets up the namespaces to be used in the query
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX tt: <http://www.trisotech.com/graph/1.0/element#>
PREFIX ttr: <http://www.trisotech.com/graph/1.0/elementRel#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dmn: <http://www.trisotech.com/graph/1.0/decision/element#>

# SPARQL queries only get the LATEST version information for all models
SELECT ?fromModel ?fromMimetype ?toModel ?toMimetype
FROM NAMED ?
WHERE {
    GRAPH ? {
        {
        # gets the CMMN -> DMN relations
            ?fromElement (ttr:semantic|ttr:copyOf) ?toElement .
            # filter out models that refer to themselves
            FILTER (!EXISTS { ?toElement rdf:type tt:Ref . } ) .
            ?fromElement ttr:owner ?fromModel .
            ?toElement ttr:owner ?toModel .
            ?fromModel ttr:mimeType ?fromMimetype .
            ?toModel ttr:mimeType ?toMimetype .

        } UNION
        {
        # gets the DMN -> DMN relations
            ?fromModel dmn:include ?toModel .
            ?fromModel ttr:mimeType ?fromMimetype .
            ?toModel ttr:mimeType ?toMimetype .
        }
    }
}
GROUP BY ?fromModel ?fromMimetype ?toModel ?toMimetype